version: '3'
services:
  app:
    build: .
    volumes:
      - .:/var/www
    command: php-fpm

  web:
    image: nginx:alpine
    volumes:
      - .:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app

  grpc:
    build: .
    volumes:
      - .:/var/www
    command: /usr/bin/rr serve -c .rr.yaml
    ports:
      - "9001:9001"

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
