<?php
# Generated by the protocol buffer compiler (spiral/php-grpc). DO NOT EDIT!
# source: proto/example.proto

namespace Example;

use Spiral\GRPC;

interface ExampleServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "example.ExampleService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param HelloRequest $in
    * @return HelloResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function sayHello(GRPC\ContextInterface $ctx, HelloRequest $in): HelloResponse;
}
